name: E-Commerce Security Scan

on: [push]

jobs:
  vuln-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Build Backend Image
        run: docker build -f docker/backend.Dockerfile -t ecommerce-backend:ci .

      - name: Scan Backend Image
        run: bash security/scanner/scan_image.sh ecommerce-backend:ci
